# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0008_auto_20180128_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFetchPerTopOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=1)),
                ('top_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorSpectrum',
            fields=[
                ('bit', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyfetchpertoporganization',
            unique_together=set([('date', 'top_organization')]),
        ),
    ]
