# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20171022_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'father')]),
        ),
    ]
