# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
