# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20171207_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='correct_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='correct_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
