# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_auto_20171207_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contracts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='errors_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='contracts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='errors_count',
            field=models.IntegerField(default=0),
        ),
    ]
