# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('fetch', '0002_detail'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('contract_date', models.DateField()),
                ('jalali_year', models.IntegerField()),
                ('jalali_month', models.IntegerField()),
                ('jalali_day', models.IntegerField()),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
                ('contract_number', models.CharField(max_length=32)),
                ('duration_year', models.IntegerField()),
                ('duration_month', models.IntegerField()),
                ('duration_day', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='location.City')),
            ],
        ),
        migrations.CreateModel(
            name='CreditSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='credit_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.CreditSource'),
        ),
        migrations.AddField(
            model_name='contract',
            name='detail_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='fetch.Detail'),
        ),
        migrations.AddField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='org.Executor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='general_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.GeneralRule'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='org.Organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.People'),
        ),
        migrations.AddField(
            model_name='contract',
            name='top_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_contracts', to='org.Organization'),
        ),
    ]
