# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171022_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
