# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171022_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
