# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171022_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='creditsource',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='generalrule',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
