# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171022_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='creditsource',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
