# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171104_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='duration_day',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='duration_month',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='duration_year',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
