# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:28
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='contract',
            name='errors',
            field=bitfield.models.BitField((('conceptual', 'مفهومی'), ('future_date', 'زمان انعقاد آینده'), ('no_end_date', 'بدون مهلت'), ('bad_end_date', 'مهلت اشتباه'), ('negative_end_date', 'مهلت منفی'), ('no_location', 'بدون مکان'), ('no_price', 'بدون قیمت'), ('no_executor', 'بدون مجری')), default=None),
        ),
    ]
