# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171202_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fetch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
