# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 11:56
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contract_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='errors',
            field=bitfield.models.BitField((('conceptual', 'خطای مفهومی ثبت شده توسط دبیر'), ('future_date', 'تاریخ انعقاد در آینده'), ('no_end_date', 'بفیلد خالی مهلت'), ('bad_end_date', 'ثبت نادرست مهلت'), ('negative_duration', 'مهلت زودتر از انعقاد'), ('no_location', 'فیلد خالی مکان'), ('no_price', 'فیلد خالی قیمت'), ('no_executor', 'فیلد خالی مجری')), default=None),
        ),
    ]
