# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='location.Province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Town'),
        ),
    ]
