# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20171102_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'town')]),
        ),
        migrations.AlterUniqueTogether(
            name='town',
            unique_together=set([('name', 'province')]),
        ),
    ]
