# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20171202_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
