# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
                ('url_code', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
    ]
