# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='with_errors_count',
            field=models.IntegerField(default=0),
        ),
    ]
